### PR TITLE
fix: remove user id requirement

### PR DESCRIPTION
**Pull request by rk185371**

### CODE REVIEW

**Comment by jonathanraftery** [comment]
Can you provide information on what you're needing to accomplish with this?

As the default implementation and the majority of custom implementations will require the user ID, it seems more appropriate for the unusual case of not needing an ID to be handled in that specific implementation.

**Comment by ridakadri** [comment]
> _ No description provided. _

We handle user session on the server side and our server team does not want to pass user info through the browser for security concerns.

**Comment by jonathanraftery** [comment]
Is it not possible to send an empty/placeholder string that is simply ignored? As the existing interface describes what the function is meant to do, we'd prefer to keep it.

**Comment by jonathanraftery** [comment]
Closing as requiring user ID is most semantically correct interface.

**Pull request closed without merging**
